[project]
name = "multi"
version = "0.1"
description = "A simple multiplication tool"
requires-python = ">= 3.10"

[project.scripts]
multi = "paquete_minimo.main:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
